name: Mirror to Read-Only Repository

on: [push, delete] # Triggers on pushes and deletions (branches/tags)

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches and tags

      - name: Push to remote mirror
        env:
          # Store the URL of the new mirror repo as a secret in the original repo's settings
          # Format for GitHub with a Personal Access Token (PAT):
          # https://<YOUR_USERNAME_OR_BOT_USERNAME>:${{ secrets.MIRROR_PAT }}@github.com/<USERNAME_OR_ORG>/<MIRROR_REPOSITORY_NAME>.git
          TARGET_REPO_URL: ${{ secrets.TARGET_REPO_URL_WITH_PAT }}
        run: |
          git remote add mirror "$TARGET_REPO_URL"
          # The --mirror flag handles pushing all branches and tags, and force pushing if necessary to match.
          git push --mirror mirror
